// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJLf392K-E7PXEmYqoyUmBymL-Ty3jl4',
    appId: '1:517367558487:web:fd0cc44f7cd33e2a190e12',
    messagingSenderId: '517367558487',
    projectId: 'binformed-24',
    authDomain: 'binformed-24.firebaseapp.com',
    storageBucket: 'binformed-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmzTYp1XzqD8BHjh_0QvBosf0EMbPKmag',
    appId: '1:517367558487:android:3c90ba727dabb725190e12',
    messagingSenderId: '517367558487',
    projectId: 'binformed-24',
    storageBucket: 'binformed-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEpkJOLWgpINxLs_aTh3GO3H2vXVnNoqY',
    appId: '1:517367558487:ios:6b184e44e10703c5190e12',
    messagingSenderId: '517367558487',
    projectId: 'binformed-24',
    storageBucket: 'binformed-24.appspot.com',
    iosBundleId: 'com.example.binformed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEpkJOLWgpINxLs_aTh3GO3H2vXVnNoqY',
    appId: '1:517367558487:ios:cb7067273349fdbe190e12',
    messagingSenderId: '517367558487',
    projectId: 'binformed-24',
    storageBucket: 'binformed-24.appspot.com',
    iosBundleId: 'com.example.binformed.RunnerTests',
  );
}
